import random

def countryCapitals():
    return { # 202 countries with capitals
# Countries name starting from "A"
            "Afghanistan" : "Kabul",
            "Albania" : "Tirana",
            "Algeria" :  "Algiers",
            "Andorra" : "Andorra la Vella",
            "Angola" : "Luanda",
            "Antigua and Barbuda" : "Saint John's",
            "Argentina" : "Buenos Aires",
            "Armenia" : "Yerevan",
            "Australia" : "Canberra",
            "Austria" : "Vienna",
            "Azerbaijan" : "Baku",
# Countries name starting from "B"
            "Bahamas" : "Nassau",
            "Bahrain" : "Manama",
            "Bangladesh" : "Dhaka",
            "Barbados" : "Bridgetown",
            "Belarus" : "Minsk",
            "Belgium" : "Brussels",
            "Belize" : "Belmopan",
            "Benin" : "Porto-Novo",
            "Bhutan" : "Thimphu",
            "Bolivia" : "La Paz",
            "Bosnia and Herzegovina" :"Sarajevo",
            "Botswana" : "Gaborone",
            "Brazil" : "Brasilia",
            "Brunei" : "Bandar Seri Begawan",
            "Bulgaria" : "Sofia",
            "Burkina Faso" : "Ouagadougou",
            "Burundi" : "Gitega",
# Countries name starting from "C"
            "Cabo Verde" : "Praia",
            "Cambodia" : "Phnom Penh",
            "Cameroon" : "Younde",
            "Canada" : "Ottawa",
            "Central African Republic" : "Bangui",
            "Chad" : "N'Djamena",
            "Chile" : "Santiago",
            "China" : "Beijing",
            "Colombia" : "Bogota",
            "Comoros" : "Moroni",
            "Costa Rica" : "San Jose",
            "Cote d'Ivore" : "Yamoussoukro",
            "Croatia" : "Zagreb",
            "Cuba" : "Havana",
            "Cyprus" : "Nicosia",
            "Czechia" : "Prague",
# Countries name starting from "D"
            "Denmark" : "Copenhagen",
            "Democratic Republic of Congo" : "Kinshasa",
            "Djibouti" : "Djibouti",
            "Dominica" : "Roseau",
            "Dominican Republic" : "Santo Domingo",
# Countries name starting from "E"
            "Ecuador" : "Quito",
            "Egypt" : "Cairo",
            "El Savador" : "San Savador",
            "Equitorial guinea" : "Oyala(seat of government), Malabo(de jure)",
            "Entirea" : "Asmara",
            "England" : "London",
            "Estonia" : "Tallinn",
            "Eswatini" : "Mbabane(administrative), Lobamba(legislative, royal)",
            "Ethiopia" : "Addis Ababa",
# Countries name starting from "F"
            "Fiji" : "Suva",
            "Finland" : "Helsinki",
            "France" : "Paris",
# Countries name starting from "G"
            "Gabon" : "Libreville",
            "Gambia" : "Banjul",
            "Georgia" : "Tbilisi",
            "Germany" : "Berlin",
            "Ghana" : "Accra",
            "Greece" : "Athens",
            "Grenada" : "Saint George's",
            "Guatemala" : "Guatemala City",
            "Guinea" : "Conakry",
            "Guinea-Bissau" : "Bissau",
            "Guyana" : "Georgetown",
# Countries name starting from "H"
            "Haiti" : "Port-au-Prince",
            "Honduras" : "Tegucigalpa",
            "Hungary" : "Budapest",
# Countries name starting from "I"
            "Iceland" : "Reykjavik",
            "India" : "New Delhi",
            "Indonesia" : "Jakarta",
            "Iran" : "Tehran",
            "Iraq" : "Baghdad",
            "Ireland" : "Dublin",
            "Israel" : "Jerusalem",
            "Italy" : "Rome",
# Countries name starting from "J"
            "Jamica" : "Kingston",
            "Japan" : "Tokyo",
            "Jordan" : "Amman",
# Countries name starting from "K"
            "Kazakhstan" : "Nur-Sultan",
            "Kenya" : "Nairobi",
            "Kiribati" : "Tarawa",
            "Kosovo" : "Pristina",
            "Kuwait" : "Kuwait City",
            "Kyrgystan" : "Bishek",
# Countries name starting from "L"
            "Laos" : "Vientiane",
            "Latvia" : "Riga",
            "Lebanon" : "Beirut",
            "Lesotho" : "Maseru",
            "Liberia" : "Monrovia",
            "Libya" : "Tripoli",
            "Liechtenstein" : "Vaduz",
            "Lithuania" : "Vilnius",
            "Luxemborg" : "Luxemborg",
# Countries name starting from "M"
            "Madagascar" : "Antananarivo",
            "Malawi" : "Lilongwe",
            "Malaysia" : "Kuala Lumpur",
            "Maldives" : "Male",
            "Mali" : "Bamako",
            "Malta" : "Valleta",
            "Marshall Islands" : "Majuro",
            "Mauritania" : "Nouakchott",
            "Mauritius" : "Port Louis",
            "Mexico" : "Mexico City",
            "Micronesia" : "Palikir",
            "Moldova" : "Chisinau",
            "Monaco" : "Monaco",
            "Mongolia" : "Ulanbaatar",
            "Montegro" : "Podgorica",
            "Morocco" : "Rabat",
            "Mozambique" : "Maputo",
            "Myanmar" : "Nyapyidaw",
# Countries name starting from "N"
            "Namibia" : "Windhoek",
            "Nauru" : "Yaren District",
            "Nepal" : "Kathmandu",
            "Netherlands" : "Amsterdam",
            "New Zealand" : "Wellington",
            "Nicaragua" : "Managua",
            "Niger" : "Niamey",
            "Nigeria" : "Abuja",
            "North Korea" : "Pyongyang",
            "North Macedonia" : "Skopje",
            "Northern Ireland" : "Belfast",
            "Norway" : "Oslo",
# Countries name starting from "O"
            "Oman" : "Muscat",
# Countries name starting from "P"
            "Pakistan" : "Islamabad",
            "Palau" : "Ngerulmud",
            "Palestine" : "Jerusalem(East)",
            "Panama" : "Panama City",
            "Papua New Guinea" : "Port Moresby",
            "Paraguay" : "Asuncion",
            "Peru" : "Lima",
            "Philippines" : "Manila",
            "Poland" : "Warsaw",
            "Portugal" : "Lisbon",
# Countries name starting from "Q"
            "Qatar" : "Doha",
# Countries name starting from "R"
            "Republic of Congo" : "Brazzavallie",
            "Romania" : "Bucharest",
            "Russia" : "Moscow",
            "Rwanda" : "Kigali",
# Countries name starting from "S"
            "Saint Kittis and Nevis" : "Basseterre",
            "Saint Lucia" : "Castries",
            "Saint Vinceint and the Grendaines" : "Kingstown",
            "Samoa" : "Apia",
            "San Marino" : "San Marino",
            "Sao Tome and Principe" : "Sao Tome",
            "Scotland" : "Edinburgh",
            "Saudi Arabia" : "Riyadh",
            "Senegal" : "Dakar",
            "Sebia" : "Belgarde",
            "Seychelles" : "Victoria",
            "Sierra Leone" : "Freetown",
            "Singapore" : "Singapore",
            "Slovakia" : "Bratislava",
            "Slovenia" : "Ljubljana",
            "Solomon Islands" : "Honiara",
            "Somalia" : "Mogadishu",
            "South Africa" : "Pretoria(administrative), Cape Town(legislative) and Bloemfontein(judicial)",
            "South Korea" : "Seoul",
            "South Sudan" : "Juba",
            "Spain" : "Madrid",
            "Sri Lanka" : "Sri Jayawardenpura Kotte",
            "Sudan" : "Khartoum",
            "Suriname"  : "Paramaribo",
            "Sweden" : "Stockholm",
            "Switzerland" : "Bern",
            "Syria" : "Damascus",
# Countries name starting with "T"
            "Taiwan" : "Taipei",
            "Tajikistan" : "Dushanbe",
            "Tanzania" : "Dodoma",
            "Thailand" : "Bangkok",
            "Timor-Leste" : "Dili",
            "Togo" : "Lome",
            "Tonga" : "Nukuʻalofa",
            "Trinidad and Tobago" : "Port of Spain",
            "Tunisia" : "Tunis",
            "Turkey" : "Ankara",
            "Turkmenistan" : "Ashgabat",
            "Tuvalu" : "Funafuti",
# Countries name starting with "U"
            "Uganda" : "Kampala",
            "Ukraine" : "Kyiv",
            "United Arab Emirates" : "Abu Dhabi",
            "United Kingdom" : "London",
            "United States of America" : "Washington D.C.",
            "Uruguay" : "Montevideo",
            "Uzbekistan" : "Tashkent",
# Countries name starting with "V"
            "Vanuatu" : "Port Vila",
            "Vatican City" : "Vatican City",
            "Venezuela" : "Caracas",
            "Vietnam" : "Hanoi",
# Countries name starting with "W"
            "Wales" : "Cardiff",
# Countries name starting with "Y"
            "Yemen" : "Sana'a",
# Countries name starting with "Z"
            "Zambia" : "Lusaka",
            "Zimbabwe" : "Harare"}